ALTER TABLE t_comment
  MODIFY C_ID INT(10) AUTO_INCREMENT;
ALTER TABLE t_category_detail
  MODIFY C_ID INT(10) AUTO_INCREMENT;
ALTER TABLE t_event
  MODIFY C_ID INT(10) AUTO_INCREMENT;
ALTER TABLE t_event_att
  MODIFY C_ID INT(10) AUTO_INCREMENT;
ALTER TABLE t_like
  MODIFY C_ID INT(10) AUTO_INCREMENT;
ALTER TABLE t_user
  MODIFY C_ID INT(10) AUTO_INCREMENT;
